name: CI/CD

on:
  push:
    branches:
      - "*"
    tags:
      - "*"
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
      - name: install requirements
        run: |
          python -m pip install -U pip setuptools wheel
          python -m pip install pre-commit tox
      - name: run pre-commit
        run: pre-commit run -a
#      - name: mypy
#        run: |
#          cd flight
#          tox -e mypy

  safety-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: install requirements
        run: |
          python -m pip install --upgrade pip setuptools
          python -m pip install '.[all]'
          python -m pip install safety
      - name: run safety check
        run: safety check

  test-flight:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.11", "3.12"]
    name: "Test Flight on py${{ matrix.python-version }} x ${{ matrix.os }} "
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - run: python -m pip install -U pip setuptools
      - run: python -m pip install tox
      - name: run flight_tests
        run: |
          tox -e py